version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: quest-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - quest-network-dev

volumes:
  mongodb_dev_data:

networks:
  quest-network-dev:
    driver: bridge
